services:
  api:
    image: tomyj/hackaton:api
    container_name: hackaton-api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: hackaton-db
    build:
      context: ./bdd
      dockerfile: Dockerfile
    image: tomyj/hackaton:db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tomyj
      MYSQL_PASSWORD: tomyj123
    volumes:
      - mysql_data:/var/lib/mysql
  front:
    image: tomyj/hackaton-front
    container_name: hackaton-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  mysql_data: