services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomyj/hackaton:db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tomyj
      MYSQL_PASSWORD: tomyj123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: